# Generated by Django 4.0.4 on 2022-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='opisanie',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
