# Generated by Django 4.0.3 on 2022-04-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_schedules_alter_aboutus_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='date',
        ),
    ]
